savedFORMAT: 1A
HOST: http://polls.apiblueprint.org/

# VMP

Service Oriented Architecture specified for the VMP project.

#######################
# Group Documents
#######################

## Documents Collection [/documents]

### List Documents DRAFT [GET /documents{?searchQuery,page,pageSize,sort,sortOrder}]
Returns the documents list.

+ Parameters
  + searchQuery: `{function:"VMP_VND", entityId:123,docTypeId: "GENDOC",owner: 234,insertDate: "2016-02-05",signingDate: "2016-02-05",validityDate: "2016-02-05"}`  (object, required) - json filter
  + page: 1 (optional, number) - The page of results to return
  + sort: description (optional) - Sorting order
  + pageSize: 25 (optional, number) - Amount of results to return

+ Response 200 (application/json)
  + Attributes (DocumentSearchResult)

### Document types DRAFT[GET /documents/types{?searchQuery}]
Return the document's types.

+ Parameters
  + searchQuery: `{function:"VMP_VND", docType:"GENDOC"}` (object) - json filter

+ Response 200 (application/json)
  + Attributes (DocumentTypes)

### Document Owner DRAFT[GET /documents/owner]
Return the document's owner.

+ Response 200 (application/json)
  + Attributes (DocumentOwner)

## Function &#40Entity Types&#41 [/functions]


### Upload Document linking it to a function  DRAFT [POST /functions/{functionId}/documents]
Creates a new document linking it to a function.

+ Parameters
    + functionId: `VMP_VND` (Function1, required) - id of the function

+ Request (multipart/form-data)

    + Attributes (DocumentUploadBodyET)

+ Response 201 (application/json)
    + Headers
          Location: http://domain/functions/{functionId}/documents/documents/10
    + Attributes (DocumentUploadedET)

+ Response 400
    Returned when input does not pass validation.
    + Body

+ Response 500
    Returned when a generic error occours.
    + Body

### Upload Document linking it to an entity DRAFT [POST /functions/{functionId}/{entityId}/documents]
Creates a new document linking it to an entity.

+ Parameters
    + functionId: `VMP_VND` (Function1, required) - id of the function
    + entityId: 123 (number, required) - id of the entity

+ Request (application/json)
    + Headers
        Content-Type: multipart/form-data
    + Attributes (DocumentUploadBodyE)

+ Response 201 (application/json)
    + Headers
          Location: http://domain/functions/{functionId}/{entityId}/documents/10
    + Attributes (DocumentUploadedE)

+ Response 400
    Returned when input does not pass validation.
    + Body

+ Response 500
    Returned when a generic error occours.
    + Body

###Download Document linked to a function  DRAFT [GET /functions/{functionId}/documents/{id}]
Returns the document detail assigned to a function.

+ Parameters
    + functionId: `VMP_VND` (Function1, required) - id of the function
    + id: 12 (number, required) - id of the document

+ Response 200 (application/XYZ)
    + Body

+ Response 404
    Returned when the required resource cannot be found.
    + Body

+ Response 500
    Returned when a generic error occours.
    + Body

###Download Document linked to an entity DRAFT [GET /functions/{functionId}/{entityId}/documents/{id}]
Returns the document detail assigned to an entity.

+ Parameters
    + functionId: `VMP_VND` (Function1, required) - id of the function
    + entityId: 123 (number, required) - id of the entity
    + id: 12 (number, required) - id of the document

+ Response 200 (application/XYZ)
    + Body

+ Response 404
    Returned when the required resource cannot be found.
    + Body

+ Response 500
    Returned when a generic error occours.
    + Body

### Delete document linked to a function  DRAFT[DELETE /functions/{functionId}/documents/{id}]
Deletes a document assigned to a function.

+ Parameters
    + functionId: `VMP_VND` (Function1, required) - id of the function
    + id: 12 (number, required) - id of the document

+ Response 204
    Returned when the resource is successfully deleted.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete document linked to an entity DRAFT[DELETE /functions/{functionId}/{entityId}/documents/{id}]
Deletes a document assigned to an entity.

+ Parameters
    + functionId: `VMP_VND` (Function1, required) - id of the function
    + entityId: 123 (number, required) - id of the entity
    + id: 12 (number, required) - id of the document

+ Response 204
    Returned when the resource is successfully deleted.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


#######################
# Group Vendor/Subcontractor
#######################

## Vendor/Subcontractor collection [/verdors{?searchQuery,page,sort,pageSize,sortOrder}]

Takes a `searchQuery` parameter object defined as follows
  + code (optional,string) - vendor/subcontractor code
  + name (optional,string) - vendor/subcontractor name
  + function (optional,string) - code of requested function (VMP_VND for Vendors, VMP_SUB for Subcontractors)
  + status (optional,String) - vendor/subcontractor status code


### List Vendor/Subcontractor [GET]
Returns the vendors/subcontractors list.

+ Parameters
  + searchQuery: {} (object, required) - json filter
  + page: 1 (optional, number) - The page of results to return
  + sort: name (enum[string], optional) - Sorting field
        + Members
            + name
            + code
            + address
            + status
            + vatnumber
  + sortOrder: asc (enum, optional) - Sorting order
        + Members
            + asc
            + desc
  + pageSize: 25 (optional, number) - Amount of results to return

+ Response 200 (application/json)
  + Attributes (VendorSearchResult)


### Create Vendor/Subcontractor [POST]
Creates a new vendor/subcontractor.

This action is available only to `VMPADMIN` rolee.


+ Request (application/json)

    + Attributes (VendorInsert)

+ Response 201 (application/json)

    + Headers

            Location: /vendors/123

    + Attributes (Vendor1)

+ Response 400
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


## Vendor/Subcontractor [/vendors/{id}]

+ Parameters
  + id: 1 (required) - id of the requested vendor/subcontractor

+ Attributes (Vendor1)

### Read Vendor/Subcontractor [GET]
Used to retrieve vendor/subcontractor detail.

+ Response 200 (application/json)

    + Attributes (Vendor1)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Vendor/Subcontractor [PUT /vendors/{id}]
This action is available only to `VMPADMIN` role.

+ Parameters
    + id: 1 (required, number) - id of the vendor/subcontractor

+ Request (application/json)
  + Attributes (Vendor1)

+ Response 200

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Vendor/Subcontractor [DELETE]
This action is available only to `VMPADMIN` role.

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


#######################
# Group Vendor Contact
#######################

## Vendor Contact collection [/contacts{?searchQuery,page,sort,pageSize,sortOrder}]

Takes a `searchQuery` parameter object defined as follows
  + code (optional,String) - contact id
  + name (optional,String) - contact name (last name + fitst name)
  + vendorcode (optional,string) - vendor id
  + vendorname (optional,string) - vendor name

### List Vendor Contact [GET]
Returns the vendor contacts list.

+ Parameters
  + searchQuery: {} (object, required) - json filter
  + page: 1 (optional, number) - The page of results to return
  + sort: lname (enum[string], optional) - Sorting field
        + Members
            + vendorcode
            + name (default)
            + email
            + role
            + code
  + sortOrder: asc (enum, optional) - Sorting order
        + Members
            + asc
            + desc
  + pageSize: 25 (optional, number) - Amount of results to return

+ Response 200 (application/json)
  + Attributes (VendorContactSearchResult)


### Create Vendor Contact [POST]
Creates a new vendor contact.

This action is available only to `VMPADMIN` rolee.


+ Request (application/json)

    + Attributes (VendorContactInsert)

+ Response 201 (application/json)

    + Headers

            Location: /contacts/123

    + Attributes (VendorContact1)

+ Response 400
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


## Vendor Contact [/contacts/{id}]

+ Parameters
  + id: 1 (required) - id of the requested vendor contact

+ Attributes (VendorContact1)

### Read Vendor Contact [GET]
Used to retrieve vendor contact detail.

+ Response 200 (application/json)

    + Attributes (VendorContact1)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update Vendor Contact [PUT /contacts/{id}]
This action is available only to `VMPADMIN` role.

+ Parameters
    + id: 1 (required, number) - id of the vendor contact

+ Request (application/json)
  + Attributes (VendorContact1)

+ Response 200

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete Vendor Contact [DELETE]
This action is available only to `VMPADMIN` role.

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#######################
# Group Vendor Employees
#######################

## Employees collection [/employees{?searchQuery,page,sort,pageSize,sortOrder}]

Takes a `searchQuery` parameter object defined as follows
  + revid (optional, number) - revision of the Employees Department
  + oucode (optional, string) - id of the employees department
  + sbc1id (optional, number) - subcontractor1 id
  + sbc2id (optional, number) - subcontractor2 id
  + vendorid (optional,string) - vendor id
  + vendorname (optional, string) - 
  + lastname (optional,string) - last name of the employee
  + firstname (optional,string) - first name of the employee
  + fiscalcode (optional, string) - fiscal code of the employee
  + userid (optional, string) - user id of the employee
  + empid (optional,String) - employee id

### List Vendor Employees [GET]
Returns the vendor contacts list.

+ Parameters
  + searchQuery: {} (object, required) - json filter
  + page: 1 (optional, number) - The page of results to return
  + sort: empid (enum[string], optional) - Sorting field
        + Members
            + vendorid
            + empid (default)
  + sortOrder: asc (enum, optional) - Sorting order
        + Members
            + asc
            + desc
  + pageSize: 25 (optional, number) - Amount of results to return

+ Response 200 (application/json)
  + Attributes (ProfileDetail1)


### Create vendor employee DRAFT [POST]
Creates a new vendor employee.

+ Request (application/json)

    + Attributes (ProfileCreate)

+ Response 201 (application/json)

    + Attributes (ProfileDetail1)

+ Response 400
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body when a generic error occours.
    + Body



## Employees [/employees/{id}]

+ Parameters
  + id: 1 (required) - id of the requested vendor employee

### Read Vendor Employees [GET]
Used to retrieve vendor employee detail.

+ Response 200 (application/json)

    + Attributes (ProfileDetail1)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update vendor employee [PUT]

Updates a vendor employee.

+ Request (application/json)

    + Attributes (ProfileDetail1)

+ Response 200 (application/json)

    + Attributes (ProfileDetail1)

+ Response 400
    Returned when input does not pass validation.

    + Body

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete vendor employee [DELETE]

Deletes the specified vendor employee.

+ Request (application/json)

    + Attributes ()

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


#######################
# Group Lookup Lists
#######################

## Countries collection [/lookup/countries]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: 1
          + description: Italy
      + (object)
          + id: 2
          + description: Germany
      + (object)
          + id: 3
          + description: Austria
      + (object)
          + id: 4
          + description: Spain
  + Include PaginationData1


### List countries [GET]

The list countries.

+ Response 200 (application/json)
  + Attributes (Countries collection)


## Commodity Families collection [/lookup/commodityfamilies]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: 1
          + description: Family B Site Maintenance
      + (object)
          + id: 2
          + description: Family F Construction
      + (object)
          + id: 3
          + description: Family G Environmental
      + (object)
          + id: 4
          + description: Family H4 Connectivity
  + Include PaginationData1


### List commodity families [GET]

The list commodity families.

+ Response 200 (application/json)
  + Attributes (Commodity Families collection)

## Contract types collection [/lookup/contracttypes]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: 1
          + description: Master / Base Agreements / Participation Agreement PA Equipment Agreements
      + (object)
          + id: 2
          + description: Statements of Work SOWs Equipment Agreements
      + (object)
          + id: 3
          + description: Statements of Work SOWs Goods Agreements
      + (object)
          + id: 4
          + description: Master / Base Agreements / Participation Agreement PA Participation Agreements
  + Include PaginationData1


### List contract types [GET]

The list contract types.

+ Response 200 (application/json)
  + Attributes (Contract types collection)


## Data Privacy Roles collection [/lookup/dataprivacyroles]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: 1
          + description: Incaricato
      + (object)
          + id: 2
          + description: SysAdm
  + paginationData (object, required) - Informations required for pagination
        + count: 2 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice

### List Data Privacy Roles [GET]

The list data privacy roles.

+ Response 200 (application/json)
  + Attributes ( Data Privacy Roles collection)


## Functions collection [/lookup/functions{?searchQuery}]

+ Parameters
  + searchQuery: `{function:"VMP_VND"}` (object) - json filter

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: VMP_CONT
          + description: Contact
      + (object)
          + id: VMP_VND
          + description: Vendor
      + (object)
          + id: VMP_CNTR
          + description: Contract Management
  + paginationData (object, required) - Informations required for pagination
        + count: 3 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List Functions [GET]

The list of functions.

+ Response 200 (application/json)
  + Attributes ( Functions collection)

## Languages collection [/lookup/languages]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: 1
          + description: English
      + (object)
          + id: 2
          + description: French
      + (object)
          + id: 3
          + description: Italian
  + paginationData (object, required) - Informations required for pagination
        + count: 3 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List Languages [GET]

The list of languages.

+ Response 200 (application/json)
  + Attributes ( Languages collection)


## Resource Types collection [/lookup/resourcetypes]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: 1
          + description: T&T
      + (object)
          + id: 2
          + description: Vendor
  + paginationData (object, required) - Informations required for pagination
        + count: 2 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List Resource Types [GET]

The list of resource types.

+ Response 200 (application/json)
  + Attributes ( Resource Types collection)


## Schedule status collection [/lookup/schedulestatus]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: 1
          + description: Approved
      + (object)
          + id: 2
          + description: New entry
      + (object)
          + id: 3
          + description: Under approval
  + paginationData (object, required) - Informations required for pagination
        + count: 3 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List Schedule status [GET]

The list of schedule status.

+ Response 200 (application/json)
  + Attributes ( Schedule status collection)

## Vendor status collection [/lookup/vendorstatus]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: A
          + description: Active
      + (object)
          + id: B
          + description: Blocked
      + (object)
          + id: M
          + description: Marked for deletion
  + paginationData (object, required) - Informations required for pagination
        + count: 3 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List Vendor status [GET]

The list of vendor status.

+ Response 200 (application/json)
  + Attributes ( Vendor status collection)


#######################
# Data Structures
#######################

## PaginationData1 (object)
+ paginationData (object, required) - Informations required for pagination
    + count: 3 (number,required) - total number of resources
    + pageNum: 1 (number, required) - slice of resources returned
    + pageSize: 25 (number, required) - size of the slice

## PaginationData4 (object)
+ paginationData (object, required) - Informations required for pagination
    + count: 4 (number,required) - total number of resources
    + pageNum: 1 (number, required) - slice of resources returned
    + pageSize: 25 (number, required) - size of the slice

## DocumentSearchResult (object)
+ results (array[Document1, Document2, Document3], required) - array of revisions
+ Include PaginationData1

## Document1 (object)
+ id: 1
+ name: `New_sup_R&D_L.pdf`
+ docType (DocumentType1, required)
+ function (FunctionVendor)
+ entityId: 123 (number, optional)
+ description: `New supplier R&D legal`
+ owner: `Cesarini Micaela`
+ insertDate: `2016-02-06 10.50.30`
+ signingDate: `2016-02-06`
+ validityDate: `2016-02-06`

## Document2 (object)
+ id: 2
+ name: `Result_SVCS_TSC_NTT_20151103.xls`
+ docType (DocumentType2, required)
+ function (FunctionVendor)
+ entityId: 123 (number, optional)
+ description: `performance NTT Data Austria`
+ owner: `Panseri Gianluigi`
+ insertDate: `2016-02-08 10.50.30`

## Document3 (object)
+ id: 3
+ name: `Supplier_questioinnaire_BRUTTI.pdf`
+ docType (DocumentType3, required)
+ function (FunctionVendor)
+ description: `Supplier questioinnaire BRUTTI L`
+ owner: `Panseri Gianluigi`
+ insertDate: `2016-02-10 10.50.30`
+ signingDate: `2016-02-10`

## DocumentUploadBodyET (object)
+ docType
    + id: 123 (number)
+ description: `Generic document for vendor`
+ insertDate: `2016-02-06 10.50.30`
+ signingDate: `2016-02-06`
+ validityDate: `2016-02-06`
+ file: `documento`

##DocumentUploadedET (object)
+ id: 12
+ docType
    + id: 123 (number)
+ description: `Generic document for vendor`
+ insertDate: `2016-02-06 10.50.30`
+ signingDate: `2016-02-06`
+ validityDate: `2016-02-06`

## DocumentUploadBodyE (object)
+ docType
    + id: 123 (number)
+ description: `Generic document for vendor`
+ insertDate: `2016-02-06 10.50.30`
+ signingDate: `2016-02-06`
+ validityDate: `2016-02-06`
+ file: `documento`

## DocumentUploadedE (object)
+ docType
    + id: 123 (number)
+ description: `Generic document for vendor`
+ insertDate: `2016-02-06 10.50.30`
+ signingDate: `2016-02-06`
+ validityDate: `2016-02-06`

##DocumentType1 (object)
+ id: `DPL`
+ description: `DPL`

##DocumentType2 (object)
+ id: `IBMCHE`
+ description: `IBM Checklist`

##DocumentType3 (object)
+ id: `SUPQUE`
+ description: `Supplier questioinnaire`

##DocumentType4 (object)
+ id: `GENDOC`
+ description: `Generic document`

##DocumentTypes (object)
+ results (array[DocumentType1, DocumentType2, DocumentType3, DocumentType4], required) - array of document types
+ Include PaginationData4

##DocumentOwner (object)
+ results (array, required) - array of document's owner
    + Mario Rossi (string)
    + Giovanni Linzi (string)
    + Alberto Moresco (string)
    + Anna Baggio (string)
+ Include PaginationData4

##Function1 (string)
    + Members
        + `VMP_VND`
        + `VMP_VEMP`
        + `VMP_CNTR`
        + `VMP_CONT`

##FunctionVendor (object)
+ id: `VMP_VND`
+ description: `Vendor`

##FunctionVendorEmployee (object)
+ id: `VMP_VEMP`
+ description: `Vendor Employee`

##FunctionContract (object)
+ id: `VMP_CNTR`
+ description: `Contract ??Management??`

##FunctionContact (object)
+ id: `VMP_CONT`
+ description: `Contact`

##Functions (object)
+ results (array[FunctionVendor, FunctionVendorEmployee, FunctionContract, FunctionContact], required) - array of entity types (functions)
+ Include PaginationData4

## ProfileBase (object)
+ firstName: `MARIO` (required, string) - First name of the profile. Must be between 2 and 50 chars long.
+ lastName: `BIANCHI` (required, string) - Last name of the profile. Must be between 2 and 50 chars long.
+ email: `mbianchi@acme.it` (required, string) - Email of the profile. Must be a valid email, as specified in RFC2822.
+ profession: `Senior Developer` (string)
+ businessUnit: `not used?` (string)
+ jobResponsability: `job responsability` (string)
+ altInternetAddress: `firstname.lastname@organization2.com` (string) - Must be a valid email, as specified in RFC2822.
+ notesAddress: `indirizzo_notes@aaaaa.it` (string) - Must be a valid email, as specified in RFC2822.
+ userId: `userid` (required, string) - Username of the profile. This field must match with the field used to authenticate on the application server.
+ employeeType: `MAI` (required, string) - Code of profile type
+ personalCode: `X123456` (required, string)
+ bluePageCode: `L123456` (required, string)
+ hiringDate: `2016-02-28` (required, string) - Hiring date of the profile. The profile can be found through queries only starting from the specified date.
+ managerRole: `true` (boolean)
+ phone (object)
    + country: `39` (string)
    + number: `12345678` (string)
+ mobilePhone (object)
    + country: `39` (string)
    + number: `1234567` (string)
+ fax (object)
    + country: `39` (string)
    + number: `3904912345678` (string)
+ vendor (VendorMini1) - Vendor object for vendor employees. Only its `id` is used.
+ functionalManager (object) - Profile of the functional manager. Only its `id` is used.
    + id: 1 (number)

## ProfileDetail (ProfileBase)
+ Include ProfilesAddresses
+ Include VendorEmployeeInfo

## ProfileCreate (ProfileDetail)
+ dismissDate: `2016-02-28` (required, string) - Dismiss date. Only considered when inserting the profile.

## ProfilesAddresses (object)
+ addresses
    + preferred (ProfileAddress) - preferred address of the user, if different from business address.
    + business (ProfileAddress) - business address of the user.

## ProfileAddress
+ street: Via Nizza 15
+ city: Torino
+ country: Italy
+ zip: 12345
+ locationId: 1 (number)


## ProfileAddressCountry
+ country: Italy
+ locationId: 1

## VendorMini1 (object)
+ id: 1 (required, number)
+ name: `IBM Italia S.p.a.` (required, string)

## VendorEmployeeInfo (object)
+ subContractor1: `123` (number, optional) - ID of the first subcontractor.
+ SubContractor1Name: `aaa` (string, optional)
+ subContractor2: `456` (number, optional) - ID of the second subcontractor.
+ SubContractor2Name: `bbb` (string, optional)
+ vendorMfirstname: `Mario` (string, optional) - firstname of the vendor manager
+ vendorMlastname: `Rossi` (string, optional) - lastname of the vendor manager
+ dprid: `aaa` (string, optional) - Data privacy role id
+ fiscalcode: `AJHC34789PAH` (string, optional)
+ hiringDate: `2016-06-15` (string, optional)
+ endDate: `2098-06-15` (string, optional)
+ nationality: `Italian` (string, optional)
+ languageId: `italian` (string, optional)
+ languageDescr: `italian` (string, optional)
+ resourceTypeId: `bbb` (string, optional)
+ resourceTypeDescr: `bbb` (string, optional)
+ active: `true` (boolean)
+ dismiss: `false` (boolean)
+ notes: `aaa bbb ccc` (string, optional)
+ networkAccessRequired: `false` (boolean)
+ accountValidityDate: `2018-06-15` (string, optional)
+ badgeRequired: `false` (boolean)
+ badgeValidityDate: `2016-02-28` (string, optional)
+ assetRequired: `true` (boolean)
+ telephonyRequired: `false` (boolean)
+ isManager: : `false` (boolean)
+ mainManager: : `false` (boolean)
+ startDate: `2018-06-17` (string, optional)
+ endDate: `2098-06-15` (string, optional)
+ employeeType: `EMP` (string, optional)
+ ouCode: `789` (number, optional)
+ ouName: `aaa` (string, optional)
+ lastUpdate: `2018-06-22` (string, optional)
+ updateBy: `Carlo Carli` (string, optional)
+ vtsReferentLastName: `Fulvio` (string, optional)
+ vtsReferentFirstName: `Simpson` (string, optional)
+ vtsReferentId: `10285` (number, optional)

## ProfileDetail1 (ProfileDetail)
+ empid: 1 (number) - id of the profile

## ProfileDetail2 (ProfileDetail)
+ empid: 2 (number) - id of the profile

## ProfileDetail3 (ProfileDetail)
+ empid: 3 (number) - id of the profile

## VendorEmployeeSearchResult (object)
+ results (array[ProfileDetail1, ProfileDetail1, ProfileDetail1], required) - array of vendor employees
+ Include PaginationData1

## Vendor1 (object)
+ id: 1 (number) - vendor/subcontractor id
+ tempCode : `00001` - temporary code
+ functionId: `VMP_VND`,`VMP_SUB` (enum[string],required) - function code VMP_VND=Vendors,VMP_SUB=Subcontractors
+ masterCode : `4000308` - master code
+ name: `A1 TELEKOM AUSTRIA AG` (required, string) - company name
+ email : `fhuntog@princeton.edu` - email
+ vatNumber : `ATU13585627`  (required, string) - vat number
+ status (VendorStatus1)  (required, string) - status object
+ address : `OBERE DONAUSTRAßE 29`  (required, string) - address
+ city : `WIEN` - city
+ state : ` ` - province or state
+ zip : `1020` - postal code
+ country (Country1) - country
+ notes : `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.` - notes
+ riskAssessment : false (boolean) - risk assessment flag
+ businessContinuity: false (boolean) - business continuity flag
+ subContratAut : false (boolean) - sub contract flag
+ providedUbis : false (boolean) provided by ubis flag
+ frameworkContract : false (boolean) - framework contract flag
+ sched25StatusId : `004` - schedule 25 status code
+ sched30StatusId : `003` - schedule 30 status code
+ schedSondrioId : `005` - schedule Sondrio code
+ vendorTypeId : `001` - vendor type code
+ infra : false (boolean) - infra flag
+ insertDate : `2016-06-20 16:23:34` (string) - insert timestamp
+ updateDate : `2016-06-21 17:30:21` (string) - update timestamp
+ updateUser : `Alberto Rossi` (string) - update timestamp


## Vendor2 (object)
+ id: 2 (required, number)
+ tempCode : `00002`
+ masterCode : `4000477`
+ name: `ADECCO ITALIA SPA` (required, string)
+ email : `example@adecco.com`
+ vatNumber : `13456789445`
+ status (VendorStatus1)
+ address : `Via Tolmezzo 15`
+ city : `Milano`
+ state : `MI` (string, optional)
+ zip : `20132`
+ country (Country2) - country
+ notes : `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.`
+ riskAssessment : false (boolean)
+ businessContinuity: false (boolean)
+ subContratAut : false (boolean)
+ providedUbis : false (boolean)
+ frameworkContract : false (boolean)
+ sched25StatusId : `004`
+ sched30StatusId : `003`
+ schedSondrioId : `005`
+ vendorTypeId : `001`
+ infra : false (boolean)
+ insertDate : `2016-06-20 16:23:34` (string) - insert timestamp
+ updateDate : `2016-06-21 17:30:21` (string) - update timestamp
+ updateUser : `Alberto Rossi` (string) - update timestamp


## Vendor3 (object)
+ id: 3 (required, number)
+ tempCode : `00002`
+ masterCode : `4000477`
+ name: `SODEXO` (required, string)
+ email : `example@sodexo.com`
+ vatNumber : `04545678944`
+ status (VendorStatus1)
+ address : `Via Gallarate 15`
+ city : `Milano`
+ state : `MI`
+ zip : `20151`
+ country (Country2) - country
+ notes : `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.`
+ riskAssessment : false (boolean)
+ businessContinuity: false (boolean)
+ subContratAut : false (boolean)
+ providedUbis : false (boolean)
+ frameworkContract : false (boolean)
+ sched25StatusId : `004`
+ sched30StatusId : `
+ schedSondrioId : ``
+ vendorTypeId : ``
+ infra : false (boolean)
+ insertDate : `2016-06-20 16:23:34` (string) - insert timestamp
+ updateDate : `2016-06-21 17:30:21` (string) - update timestamp
+ updateUser : `Alberto Rossi` (string) - update timestamp

## VendorInsert (object)
+ tempCode : `00001` - temporary code
+ functionId: `VMP_VND`,`VMP_SUB` (enum[string],required) - function code VMP_VND=Vendors,VMP_SUB=Subcontractors
+ masterCode : `4000308` - master code
+ name: `A1 TELEKOM AUSTRIA AG` (required, string) - company name
+ email : `fhuntog@princeton.edu` - email
+ vatNumber : `ATU13585627`  (required, string) - vat number
+ status (VendorStatusInsert)  (required, string) - status object
+ address : `OBERE DONAUSTRAßE 29`  (required, string) - address
+ city : `WIEN` - city
+ state : ` ` - province or state
+ zip : `1020` - postal code
+ country (Country1) - country
+ notes : `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.` - notes
+ riskAssessment : false (boolean) - risk assessment flag
+ businessContinuity: false (boolean) - business continuity flag
+ subContratAut : false (boolean) - sub contract flag
+ providedUbis : false (boolean) provided by ubis flag
+ frameworkContract : false (boolean) - framework contract flag
+ sched25StatusId : `004` - schedule 25 status code
+ sched30StatusId : `003` - schedule 30 status code
+ schedSondrioId : `005` - schedule Sondrio code
+ vendorTypeId : `001` - vendor type code
+ infra : false (boolean) - infra flag


## VendorSearchResult (object)
+ results (array[Vendor1, Vendor2, Vendor3], required) - array of Vendors/Subcontractors
+ Include PaginationData1

## VendorStatus1 (object)
+ id: `001` (required, string) - status code
+ description: `Active` - status description

## VendorStatusInsert (object)
+ id: `001` (required, string)

## VendorContact1 (object)
+ id: 1 (number) - vendor contact id
+ firstName : `Fatima` (required, string) - contact first name
+ lastName : `Cross` (required, string) - contact last name
+ companyName: `A1 TELEKOM AUSTRIA AG` (required, string) - company name
+ email : `fhuntog@princeton.edu` - main email
+ email2 : `velit.dui.semper@Nuncsedorci.org` - secondary email
+ phoneNumber : `(556) 566-8629` - phone number
+ role : `Chief Design Engineer`  (required, string) - contact role
+ address : `OBERE DONAUSTRAßE 29`  (required, string) - address
+ city : `WIEN` - city
+ state : ` ` - province or state
+ zip : `1020` - postal code
+ notes : `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.` - notes
+ vendor (VendorMini2)  (required, object) - vendor object
+ enabled : true (boolean)
+ insertDate : `2016-06-20 16:23:34` (string) - insert timestamp
+ updateDate : `2016-06-21 17:30:21` (string) - update timestamp
+ updateUser : `Alberto Rossi` (string) - update timestamp


## VendorContact2 (object)
+ id: 2 (number) - vendor contact id
+ firstName : `Wayne` (required, string) - contact first name
+ lastName : `Nash` (required, string) - contact last name
+ companyName: `Egestas Nunc Sed Institute` (string) - company name
+ email : `enim.nec@dapibusgravidaAliquam.org` - main email
+ email2 : ` ` - secondary email
+ phoneNumber : `(588) 151-2979` - phone number
+ role : `Staff Scientist`  (required, string) - contact role
+ address : `Ap #720-9780 In Ave`  (required, string) - address
+ city : `WIEN` - city
+ state : ` ` - province or state
+ zip : `1020` - postal code
+ notes : `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.` - notes
+ vendor (VendorMini3)  (required, object) - vendor object
+ enabled : true (boolean)
+ insertDate : `2016-06-20 16:23:34` (string) - insert timestamp
+ updateDate : `2016-06-21 17:30:21` (string) - update timestamp
+ updateUser : `Alberto Rossi` (string) - update timestamp


## VendorContact3 (object)
+ id: 3 (number) - vendor contact id
+ firstName : `Candace` (required, string) - contact first name
+ lastName : `Candace` (required, string) - contact last name
+ companyName: `Arcu Sed Foundation` (required, string) - company name
+ email : `enim.nec@dapibusgravidaAliquam.org` - main email
+ email2 : ` ` - secondary email
+ phoneNumber : `(588) 151-2979` - phone number
+ role : `Staff Scientist`  (required, string) - contact role
+ address : `Ap #720-9780 In Ave`  (required, string) - address
+ city : `WIEN` - city
+ state : ` ` - province or state
+ zip : `1020` - postal code
+ notes : `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.` - notes
+ vendor (VendorMini2)  (required, object) - vendor object
+ enabled : true (boolean)
+ insertDate : `2016-06-20 16:23:34` (string) - insert timestamp
+ updateDate : `2016-06-21 17:30:21` (string) - update timestamp
+ updateUser : `Alberto Rossi` (string) - update timestamp

## VendorContactInsert (object)
+ firstName : `Fatima` (required, string) - contact first name
+ lastName : `Cross` (required, string) - contact last name
+ companyName: `A1 TELEKOM AUSTRIA AG` (required, string) - company name
+ email : `fhuntog@princeton.edu` - main email
+ email2 : `fhuntog@princeton.edu` - secondary email
+ phoneNumber : `(556) 566-8629` - phone number
+ role : `Chief Design Engineer`  (required, string) - contact role
+ address : `OBERE DONAUSTRAßE 29`  (required, string) - address
+ city : `WIEN` - city
+ state : ` ` - province or state
+ zip : `1020` - postal code
+ notes : `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.` - notes
+ vendor (VendorMini2)  (required, object) - vendor object
+ enabled : true (boolean)

## VendorContactSearchResult (object)
+ results (array[VendorContact1, VendorContact2, VendorContact3], required) - array of Vendor Contacts
+ Include PaginationData1

## VendorMini2 (object)
+ id: 1 (required, number)
+ name: `IBM Italia S.p.a.` (required, string)
+ mastercode: `000025`

## VendorMini3 (object)
+ id: 406 (required, number)
+ name: `Meedoo` (required, string)
+ mastercode: `00406`

## Country1 (object)
+ id: 040 (required, string)
+ description: `Austria` (string)

## Country2 (object)
+ id: 380 (required, string)
+ description: `Italy` (string)